### ISSUE TITLE
Liquidity issues

### ISSUE THREAD

**Issue by antony** [butor/blackbird#110]
Hi.

I've run Blackbird in demo mode for a while, and it seems to work really well. I've now added the minimum $30 USD to two accounts so that I can start to see real trades.

I noticed an opportunity today but I got an error about liquidity. I understand this translates as "not enough cash to trade", but I can't see any information about which account needs more cash, and how much cash I would need.

My log gives this:

```
[ 02/09/2017 13:33:39 ]
   Bitfinex: 	959.00 / 961.00
   Bitstamp: 	950.00 / 951.01
   ----------------------------
   Bitstamp/Bitfinex:	 0.84% [target  0.80%, min -3.08%, max  0.95%]   trailing  0.87%  1/1
<Bitstamp> Looking for a limit price to fill 0.03 BTC...
<Bitstamp> order book: 7.25@$959.00
<Bitfinex> Looking for a limit price to fill 0.03 BTC...
<Bitfinex> order book: 9.25@$959.45
WARNING: Opportunity found but not enough liquidity. Trade canceled
         Target long price:  951.01, Real long price:  959.00
         Target short price: 959.00, Real short price: 959.45
```

Is there some way to understand how much liquidity I'd need to make a similar trade in future?

Apologies for raising questions as an issue - I don't see a mailing list / discussion group anywhere.

**Comment by butor** [comment]
Hi @anthony,

`Opportunity found but not enough liquidity. Trade canceled`

The liquidity we are taking about here is actually not the amount of money you are trying to trade, but what’s available on the exchanges, at the price you are targeting.

In your example there was enough liquidity on Bitfinex (_short_), but not on Bitstamp (_long_). Let's see the details:

- **on Bitfinex**
You were looking to short sell 0.03 BTC at $959.00, and according to the first entry in Bitfinex's order book the best price is:
`<Bitfinex> order book: 9.25@$959.45`
The real price ($959.45) is better for you because it's higher that what you have targeted ($959.00). Remember, here you are short selling. The higher the better.

- **on Bitstamp**
You were looking to buy 0.03 BTC at $951.01, and according to Bitstamp's order book the best price is:
`<Bitstamp> order book: 7.25@$959.00`
The real price is $7.99 more expensive than the price you were looking for. Here you are buying, so the lower the better. This $7.99 difference is above the limit defined by `PriceDeltaLimit` (default $0.10), so the whole arbitrage trade is canceled due to that slippage.

The liquidity was simply gone just before you tried to close the position on Bitstamp. Solutions to this issue: you can try to decrease `GapSec` (e.g. increase the frequency) or increase `PriceDeltaLimit` and see if it works for you.

**Comment by antony** [comment]
Hi @butor 

Thanks for your incredibly useful and comprehensive reply! This makes a lot of sense now :)

Cheers,
Antony
