### ISSUE TITLE
US short selling

### ISSUE THREAD

**Issue by jackeown** [butor/blackbird#116]
Is there any way, using this software, to make trades without a bitfinex margin account?  As of 2 months ago, bitfinex doesn't allow margin accounts for people in the US.  Does that make this program useless for me or is there some other way to run it?

**Comment by jw4wellness** [comment]
Open Corporation(s) in another country and get bank account there and register a bitfinex margin account for that corporation. Or team up with someone from another country and split profits. Who do you know in another country that you can trust?

**Comment by butor** [comment]
Yes you are correct. Unfortunately, since Blackbird requires an account on Bitfinex to short sell, you cannot use it for now if you are a US resident. This is also a problem for me.

Message from Bitfinex ([link here](https://support.bitfinex.com/hc/en-us/articles/115000580465-Can-US-Residents-Trade-on-Margin-)):

> Bitfinex provides three main services: exchange trading, margin trading, and margin funding. While exchange trading and margin funding are available for all users, unfortunately we cannot enable margin trading for verified US residents at this time.
> 
> In the past we had implemented a system that was acceptable to US regulating bodies, but for the time being be have disabled that system while we investigate a better solution for our verified US customers.

**Comment by greatwolf** [comment]
I wonder how receptive poloniex is on allowing margin short for USDT?

**Comment by jackeown** [comment]
Also, if you weren't as concerned about being market neutral, couldn't you also have a partial standing in both markets and just buy and sell instead of buying and short selling?  It'd be nice if you were able to specify a default investment and as long as you were investing less than that for arbitrage, you wouldn't need a margin account.

**Comment by butor** [comment]
@jackeown Being market neutral is the core principle of Blackbird. The fact that we are not impacted by market moves is a huge advantage.

The reason why you need to have empty BTC accounts when you start Blackbird is also for market neutrality. Look at that example ([link here](https://github.com/butor/blackbird/issues/100#issuecomment-274953764)) where $600 are lost without trading anything.

**Comment by sharkmerry7** [comment]
Hi Butor,

Been following this for a while. Almost had it setup when Bitfinex pulled US margin abilities. 

Looks like you added a beautiful checkmark for Poloniex on short selling. Does this mean US peoples can operate blackbird again? 

Thanks!

**Comment by butor** [comment]
HI @sharkmerry7 

Sorry [the exchange table](https://github.com/butor/blackbird#implemented-exchanges) on the README wasn't very clear. But there was a _Implemented_ column: a checkmark meant the exchange was implemented, otherwise it was just _considered_ as a potential exchange.

I've changed that into two tables: _Implemented_ and _Potential_.

Bottom line: Poloniex is not yet implemented.

**Comment by BigFav** [comment]
I think the lack of US support from the exchanges, and thus this application is super meaningful. I think you should consider adding this into the Readme.
