### ISSUE TITLE
Getting stuck

### ISSUE THREAD

**Issue by antony** [butor/blackbird#118]
I've been running this for a while now, and I've been seeing some activity which is quite exciting.

However I don't seem to be able to ever get past this log message:

```
   Bitfinex: 	1,232.40 / 1,232.90
   OKCoin: 	1,235.01 / 1,235.03
   Bitstamp: 	1,226.27 / 1,226.57
   Gemini: 	1,229.89 / 1,229.90
   ----------------------------
   OKCoin/Bitfinex:	-0.17% [target -0.15%, min -0.79%, max  2.07%]   trailing -0.18%  1/1
<Bitfinex> WARNING: BTC position not available, return 0.0
<OKCoin> Looking for a limit price to fill 0.00 BTC...
<OKCoin> order book: 6.94@$1,235.01
<Bitfinex> Looking for a limit price to fill 0.00 BTC...
```

Not sure how to progress - it's been stuck like this for a week now.

**Comment by antony** [comment]
As usual after I raise a bug I think I've finally figured it out - `stop_after_notrade_` exists, so I guess the trade is done, and we've exited? There is no process running.

Should there maybe be a message printed to let people know that the file existed and that the application exited?

**Comment by butor** [comment]
Thanks @antony. Something is off: you were trying to fill out 0.00 BTC orders:

`Looking for a limit price to fill 0.00 BTC...`

And you also have this warning from Bitfinex:

`WARNING: BTC position not available, return 0.0`

Do you have cash on your Bitfinex **Margin** account? And could you please send us the full log (you can hide sensitive information)? Thanks.

In any case, the system should throw an error when trying to fill out 0.00 BTC orders, which usually is the case. I wonder in which loop the program is stuck.

**Comment by antony** [comment]
Hey - thanks for the swift response.

Bitfinex balances look like this:
![bitf-margin](https://cloud.githubusercontent.com/assets/218949/23773460/2ea8cfa4-0517-11e7-9b9e-c8bdd8543365.png)

Log file is below - I don't think there was anything to censor per-se, but I did notice something very odd, which is that my OkCoin balance is showing up as $3.27 / 0.0009 BTC. This is wrong, OkCoin balance is ~$32. Not sure if it's related, but definitely important.

[blackbird_log_20170225_153725.log.gz](https://github.com/butor/blackbird/files/832446/blackbird_log_20170225_153725.log.gz)

**Comment by butor** [comment]
Thank you @antony for the log file. Two problems need to be addressed, but they have the same source: not enough money detected on your OKCoin account.

1. The balance on your OKCoin account is inaccurate. According to you, it should be ~$32 but the value captured is $3.27. I've never seen this problem before. Please make sure you do have ~$32 on the OKCoin account connected to Blackbird.

2. Regardless, we need to add a check right after an opportunity is detected between two exchanges. If one of the exchanges has a balance of less than $10 (by default, [hardcoded value](https://github.com/butor/blackbird/blob/master/src/main.cpp#L50) by the way), the trade should be canceled. This is because orders with less than $10 might be rejected by some exchanges.

The Bitfinex error `BTC position not available, return 0.0` in your log is linked to the fact that the orders weren't correctly executed in the first place, because of the low balance (look at the IDs):

```
<OKCoin> Trying to send a "buy" limit order: 0.00@$1,146.87...
<OKCoin> Done (order ID: 0)

<Bitfinex> Trying to send a "sell" limit order: 0.00@$1,160.10...
<Bitfinex> Done (order ID: 0)
```

This clearly shouldn't happen. Blackbird should raise a warning and cancel the trade.

**Comment by greatwolf** [comment]
This might have something to do with the use of `double` and comparisons in the code and the accumulated rounding error as a result.

lines main.cpp:377

    if (res.exposure == 0.0) // ...

is suppose to catch this. If `res.expose` is some small value but still greater than epsilon to not count as '`0.0`' later on at line 397

    double volumeLong = res.exposure / btcVec[res.idExchLong].getAsk();

You could end up with `volumeLong == 0.0` (eg. `res.exposure` is very small and it's being divided by some very large return value from `getAsk`).

Also see http://stackoverflow.com/q/6722293/234175

**Comment by antony** [comment]
Thanks for the useful info! I've included my OkCoin balance here as a proof that $3.27 is incorrect - I think it was probably closer to $32 at the time - so it's very possible the rounding problem mentioned above:

![balances](https://cloud.githubusercontent.com/assets/218949/23787120/64f77172-0568-11e7-8881-0f13ea6bb66c.png)

I agree - unless the trades are actually executed, the program shouldn't continue. It's somewhat hard to understand from the logs, but I'm getting better at understanding them now :)

**Comment by butor** [comment]
Interesting. Thanks @antony and @greatwolf.

@greatwolf how can we overcome this rounding problem? Any recommendations? In trading systems I've seen the `float` or `double` prices are converted into `int`.

For example `"float" 342.89` would become `"unsigned int" 34289`. But I guess that's a big change in the code.

Also, the check at [line 377](https://github.com/butor/blackbird/blob/master/src/main.cpp#L377) is not enough. We should also check before any trade that the exposure is not less than $10.00. I'll take a look.

**Comment by greatwolf** [comment]
The typical way to handle this is to just not use 'floating' point types especially to represent units of money. I recommending checking out the following resources as they provide a much better explanation than I can:

 - https://spin.atomicobject.com/2014/08/14/currency-rounding-errors
 - http://stackoverflow.com/a/3730040/234175

As for solutions, using `int`'s or perhaps a fix-point arithmetic library would be the way to go. Unfortunately this will involve a pretty big change since floats are used pretty liberally throughout the codebase.

For now, just adding the extra check to fix the bug as a temporary measure.
