### ISSUE TITLE
What would be the cost of adding other currencies?

### ISSUE THREAD

**Issue by AdrienGiboire** [butor/blackbird#132]
_Warning note: I'm a rookie in fintech._

Hi there! Thanks for the good job with Blackbird that looks awesome and _almost_ exactly what I was looking for.

After reading and stumbling and rumbling, I got to think: why is blackbird only dealing with BTC markets? What would it needs to extend to say ETH and other serious altcoins?

**Comment by greatwolf** [comment]
The reason is BTC is the one with the highest crypto marketcap and the most liquidity across exchanges. However, this could change if blockstream isn't ejected from their leadership position as this war comes to a head.

Regard altcoin support, it's going to take quite a bit of work. Blackbird assumes it's arbitraging between USD and BTC. As a result a lot of places has hardcoded currency symbols and values. The exchange api bindings doesn't support calls with a different trading pair.

**Comment by Newar417** [comment]
Re Volume: I successfully run the spreadbot1000 for arbitrage on alts. Volume has not been an issue for the last year or so.

**Comment by AdrienGiboire** [comment]
OK. I did not think about the hard coded parts. Thanks :)
