### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by rasheedmoore** [butor/blackbird#136]
getting this output after running ./blackbird

according to the log file I am connected

--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 03/23/2017 22:30:56

Connected to database 'blackbird.db'

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.50%

[ Current balances ]
   Bitfinex:	0.00 USD	0.000000 BTC
   Kraken:	49.39 USD	0.000000 BTC

**Comment by greatwolf** [comment]
Is there another process that's accessing blackbird.db?(for example, two instances of blackbird running?) Can you try copying the blackbird.db file elsewhere, delete the original and move it back again?

According to SQLite's doc, the last issued SQL statement may not complete unless `sqlite3_reset` or `sqlite3_finalize` is called. But this shouldn't be an issue since blackbird only uses `sqlite3_exec` when executing SQL statements.
