### ISSUE TITLE
Why not using order book to get quotes ?

### ISSUE THREAD

**Issue by bejito** [butor/blackbird#157]
I am probably missing something here, but I don't understand why we are making a call to the ticker api to get the market prices whereas we could directly obtain them through the order books. 
This way, we would have bigger chances to avoid slippage issues, and we would have one less call.

**Comment by greatwolf** [comment]
When orders are placed it uses information from `getLimitPrice` which actually does query the orderbook. The ticker for quote transmits less information than the orderbook but still enough for the things we want.

It's certainly possible to use the orderbook for both purposes but I didn't change it in my refactor since that's what the original code did. @butor can give some feedback on this, he might have a better rationale for doing it this way?

**Comment by butor** [comment]
@greatwolf is correct. To analyze the spread, we just need the bid/ask information that we can simply get by calling the ticker. We don't have to carry other information. Then, if (and only if) an opportunity is detected, we call the orderbook to check whether the liquidity is present and set the limit price before trading.

**Comment by bejito** [comment]
Answers my question, thx !
