### ISSUE TITLE
Ongoing cost for funding

### ISSUE THREAD

**Issue by mrd0ll4r** [butor/blackbird#160]
Hey,

I'm wondering about the running costs for obtaining funding, on bitfinex specifically.
Imagine this scenario: I  have USD 100 on bitfinex and bitstamp. I use those to enter the market. Ten days later I exit the market because I hit the target spread. I believe I made some profit, but I actually probably lost money due to the funding cost on bitfinex.

Sorry if I sound confused, I truly am. Blackbird does not take funding cost into account, correct? Could we? Should we?

**Comment by butor** [comment]
You're right @mrd0ll4r. The funding costs on Bitfinex are not taken into account, and should be.

To give a little bit of context, when I started the project in 2014 the discrepancies between exchanges were wide and short: a couple of minutes only. In this configuration, the funding fees were very small and considered included in `BitfinexFees`  (0.2% by default).
Nowadays the spreads stay open longer, up to couple of days/weeks, and the system would be more accurate if the exact funding costs were taken into account to estimate the return before trading an opportunity.

**Comment by jw4wellness** [comment]
I also wondered about this and wrote them an email. I think we can over come it.
Dear Reader,
I have some BTC in my funding wallet and I also do some margin trading. How can I make use of my own bitcoin (fund my own margin trading) so that I don't have to pay funding cost?
Their response:
Hello JW Kühn
The way it works is if the size of your position does not exceed the funds in your trading wallet, you won't have to borrow funds. 

So if we have some BTC the funding cost could be ignored.

**Comment by mrd0ll4r** [comment]
But we don't want to hold BTC at any point due to the risk of losing money on a falling course?

**Comment by jw4wellness** [comment]
That is one way to look at it. Others believe BTC is safer than USD, since
they expect the USD to collapse. See https://goldsilver.com/hidden-secrets/
(BTC is limited like gold / silver now. Where USD is like monopoly money,
They just print more as They need them.)

Anyway, I understand your point and how do we correct the funding cost
issue then?

**Comment by mrd0ll4r** [comment]
The bitfinex API has methods that should tell us about the cost for funding, e.g. [Active Funding Used in a Position](http://docs.bitfinex.com/v1/reference#rest-auth-active-funding-used-in-a-margin-position) and the related ones.
That should allow us to calculate the cost and adjust our target profit accordingly.

The problem to me is that I absolutely cannot understand what the numbers mean when I check my funding used on the website.

**Comment by jw4wellness** [comment]
If you could upload a screenshot we could have a look and maybe one of us
knows?
PS: lightshot <https://app.prntscr.com/download.html>(Click to see) is what
I use for easy screenshots. What do you use?
