### ISSUE TITLE
What counter measures do we need to take?

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#166]
Hi I noticed the warning:
"Bitfinex is currently trading at a premium due to their current banking issues. Therefore, there is a large spread (>4%) between that exchange and the other ones. That spread is unlikely going to narrow until those banking issues are resolved"

What counter measures do we need to take? Should we adjust how blackbird work since the spread will likely never close?

**Comment by butor** [comment]
One of the fundamental principles is that the prices need to "swing" between them in order to get spreads that open and then close.

If you observe that the prices difference between Bitfinex and another exchange, say ABC, always swings between two values, you can modify the parameters to capture that.

For example, if you have noticed that the spread between Bitfinex and ABC seems to always be between 4% and 10%, you can setup the system as follow:
- _enter an arbitrage trade if spread > 9%_
- _exit an arbitrage trade if spread < 5%_

**Comment by jw4wellness** [comment]
Thank you.

**Comment by jw4wellness** [comment]
Hi I finally got it compiled and now looking at it I notice in the conf
file these lines:

SpreadEntry=0.0080
SpreadTarget=0.0050

Is that the ones I should change?

So it should then be

SpreadEntry=0.0090
SpreadTarget=0.0050

Is that correct? Or are you refering to something else?

**Comment by butor** [comment]
Hi @jw4wellness,

The numbers I gave (9% and 5%) are simply made up examples between Bitfinex and an imaginary "ABC" exchange. They are not recommendations.
But basically yes, `SpreadEntry` and `SpreadTarget` are the main parameters you use to control your strategy, so if you detect a "swing" pattern between two exchanges, you would modify them to match the pattern (as in my example).

**Note**: `SpreadTarget` represents the _targeted profit_ of your strategy, and not the threshold to exit a trade. The threshold to exit a trade, `res.exitTarget` is computed [here](https://github.com/butor/blackbird/blob/master/src/check_entry_exit.cpp#L114):

`res.exitTarget = res.spreadIn - params.spreadTarget - 2.0*(res.feesLong + res.feesShort);`

**Comment by jw4wellness** [comment]
Thank you and now I am more confused.
I understand that is just suggestions so just to be clear.
If I want to

   - *enter an arbitrage trade if spread > 9%*
   - *exit an arbitrage trade if spread < 5%*

How do I do it?

*--*
*Oh, by the way!*
We are introducing a solution for people who pay too much tax. Learn More
Here: http://eepurl.com/cxT-jD​

*Talk Soon,*
*Jan-Willem Kühn*
*Bookkeeper*
www.e-galdesigns.com
Phone/Text: (226) 388-1304
Fax: (877) 709-2588
*IMPORTANT Disclaimer: *The contents of this email and any attachments are
confidential. They are intended for the named recipient(s) only. If you
have received this email by mistake, please notify the sender immediately
and do not disclose the contents to anyone or make copies thereof.

If you are not the recipient, you are hereby notified that any disclosure,
copying, distribution or taking action in connection with the contents of
this information is strictly prohibited and may be unlawful.

**Comment by jw4wellness** [comment]
Maybe we first have to break it down.
How do I change the parameter to enter a spread if it is bigger than 9%?
Change 
`SpreadEntry=0.0090`
that correct?

**Comment by butor** [comment]
`SpreadEntry=0.0090` is actually 0.90% but yes, you rationale is correct. So if you want to set the threshold entry at 9% it would be `SpreadEntry=0.0900` then.

For the exit, it will be based on the formula mentioned earlier:
`res.exitTarget = res.spreadIn - params.spreadTarget - 2.0*(res.feesLong + res.feesShort);`

So if you want to set `SpreadTarget` as a function of an exit target, you can do:
_SpreadTarget = SpreadEntry - ExitTarget - 2*(sum of exchange fees)_

I say more or less, because `SpreadEntry` is the target entry trade, whereas `res.spreadIn` is the actual entry trade that was executed. They can be different for various reasons (slippage, `trailingSpread`, etc).

**Comment by jw4wellness** [comment]
Thank you.
I am just wondering what formula to use.
If you don't mind me asking what is your strategy to make sure you profit from the spread of bitfinex even if it is so high as it is now? I looked at charts and it doesn't cross the price of okcoin anymore.

**Comment by jw4wellness** [comment]
I did some calculations and this is how it looks. so how do we enter it into our equation? 
![black 11](https://cloud.githubusercontent.com/assets/26123052/26261670/1f721174-3ca0-11e7-81d8-5ff549330e6d.jpg)
Which one of the two is correct? The spread is 
![image](https://cloud.githubusercontent.com/assets/26123052/26261704/3881270e-3ca0-11e7-9492-e3314c7bec5f.png)

**Comment by jw4wellness** [comment]
Thank you for your help. This is the purpose of my questions: **To make sure the trade exit happens.**

Let me explain:
Let's say the spread is between 4% and 9% for the last few days and it might go up to 15% or more. We don't know how it could go, but we want to prepare to benefit from that.

We also know that it is not going to switch over in the near future, so how do we profit from it? The lowest I have seen it go was 0.32908%.

As I understand the program switch over when we go below 0?
This is my log file:
```
[ 05/18/2017 13:55:15 IN MARKET: Long OKCoin / Short Bitfinex ]
   Bitfinex: 	1,916.40 / 1,918.30
   OKCoin: 	1,885.80 / 1,888.83
   Kraken: 	1,877.88 / 1,878.60
   BTC-e: 	1,820.55 / 1,827.10
   ----------------------------
   OKCoin/Bitfinex:	 1.72% [target -0.21%, min  0.60%, max  3.02%]

[ 05/18/2017 13:55:18 IN MARKET: Long OKCoin / Short Bitfinex ]
   Bitfinex: 	1,916.80 / 1,918.00
   OKCoin: 	1,885.89 / 1,888.81
   Kraken: 	1,877.88 / 1,878.60
   BTC-e: 	1,820.30 / 1,827.17
   ----------------------------
   OKCoin/Bitfinex:	 1.70% [target -0.21%, min  0.60%, max  3.02%]
```
Here the target was  -0.21% and since I thought that was never going to happen I manually exited the trades and then stopped blackbird to make sure I fix this or one will lose money by waiting for a trade to happen that didn't happen recently based on historical data. Lose money by paying unnecesarry funding costs, waiting for a trade that is probably not going to happen. 

Is my thinking making sense?

**Comment by butor** [comment]
Yes, your thinking makes sense. The prices have to "swing" between them, meaning that if an exchange, like Bitfinex now, is _constantly_ trading at a premium, the arbitrage opportunity wouldn't close. The spread has to swing between two values, which is represented by `SpreadTarget`.

It was more efficient to use `SpreadTarget` instead of `SpreadExit`, because the exit threshold is now dynamic and will adapt to the market situation.

**Comment by greatwolf** [comment]
Some good news, it looks like the Finex spread is finally closed since yesterday.

**Comment by kurt-skewton** [comment]
Hi, I am trying to compile this project on windows 10 either under mingw64 or visual studio. I am having a hard time compiling the dependencies using mingw64. May I ask what did you end doing to get that successfully compiled please? Thanks.

**Comment by greatwolf** [comment]
Some of them are easier to build under a posix emulated environment, like using MSYS2 for instance. Which dependencies are you having trouble with exactly?

**Comment by kurt-skewton** [comment]
I set up msys2 and then got the tool chain for mingw64. I am superficially familiar with the distinction between an msys2 build and a mingw64 build. Admittedly I was favoring the latter, so tried this. For msys2, I believe that
a subset of the deoendencies are provided
in packaged form. I think I would need to build jannson only afaik. 

Ultimately, what's most important for me is to get this up and running in an ide in which I can debug line by line. I am looking to use this program as such but to use it as a starting point. Hence I would prefer to have this running under MS VS. 

But I need to get some build running first.

The thing I struggled with is openssl 1.0.2. I can't get this to build out of the box and don't understand the build process well enough. 

So do you recommend I use msys2 and don't build openssl and curl at all?

**Comment by greatwolf** [comment]
For openssl, I would suggest building it under MSYS2(it's basically a bash emulator for windows) using mingw64 toolchain. Make sure mingw is accessible under MSYS2, eg. `gcc --version` should work. If it doesn't just add it to the `PATH`, for example

    PATH=$PATH:/c/your_mingw_folder/bin

To build openssl, check out INSTALL.W32 in particular the "GNU C (MinGW/MSYS)" section. For Jansson, you should be able to build it with CMake + mingw32-make(or nmake if for VS).

Since these are all C libraries, the produced dll's can work with VS too even though it's compiled using mingw.

**Comment by kurt-skewton** [comment]
OK, I'll try that. I had not realised that you
can use openss built with mingw64 when biolding downstream with VS also. 

So, you see no advantage to setting up mingw64 outside of msys2? Do you see what I mean? In my understanding you can have mingw64 stand alone. Or you can install msys2 and then install the mingw64 tool chain within msys2. Then from msys2, you have three shells: msys2, mingw32 and mingw64. It was my understanding that by using the mingw64 shell, you are basically in the relevant pure windows mingw64 environment.

**Comment by greatwolf** [comment]
The MinGW64 standalone and the mingw that you install through MSYS2 they're more or less the same toolchain. You can use the standalone MinGW inside MSYS2 by just making sure the right `PATH` are set -- you don't need two copies of MinGW.

A thing to be careful of is to not mix 32-bit with 64-bit binary. For example, if you intend to use 32-bit `cl` from VS make sure you build with version of MinGW that produces 32-bit dlls.

**Comment by kurt-skewton** [comment]
Understood, it is sufficient to install the mingw64 toolchain within msys2 using pacman. No need to double install a separate mingw64. On the other hand I am confused by your comment about the path. In my understanding msys2 intends you to use a mingw64 shell (as opposed to an msys2 shell) to build native w64 (non posix) code. Hence the windows path is not relevant. The mingw64 shell should just be set up to point to the right compiler, etc... No?

Yes understood for the bitness of the binaries. 

Do you mind me asking if you use a visual line debugger when you develop and if so which one? I personally find VS invaluable for this. 

Also I am still confused about using a mingw64 built openssl with a VS build. This must be using a static openssl right? The dynamic stuff depends on the MS runtime libs and Inthink it's very important to get that right afaicr. 

I'll try and report back in any case. Thx.

**Comment by greatwolf** [comment]
My comment on adding to `PATH` is only if you're using a standalone MinGW that you installed separately from MSYS2. In that case, MSYS2 won't know where MinGW is located thus the reason for adding MinGW to `PATH`. However, if you're installing MinGW using pacman then you probably don't need to fiddle around with this env variable. I believe pacman puts MinGW toolchain somewhere in MSYS2's subdirectories.

For debugger, I tend to just use gdb for this.

MinGW has to build openssl dynamically -- you want `libeay32.dll` and `libssl32.dll`. When you build with MinGW the dynamic libraries are linked against msvcrt.dll -- it does not use the later vc runtimes present in visual studio so this should not be a problem.

**Comment by kurt-skewton** [comment]
Still working on this. I am really trying to build this with VS 2017, I have decided. I have all the dependencies built, though with some caveats as I am always confused about when to build dlls and when to build static. Moreover I am confused about the dependencies among the curl and openssl. But I'll sort this out later when linking running the blackbird binary. 

Two issues I hit last night were that openssl 1.1 has changed the name of the libraries on Windows. 

Secondly, that is a problem, because I am running the CMake GUI and for some reason (why?), it is looking for libeay still. There are other issues  with CMake here. For instance it's not detecting curl properly. It's detecting that curl stuff is included, but is not giving me the option to add the relevant include location. Admittedly I have no idea of how CMake works. 

If I don't manage somehow, I'll end up building the solution/projects by hand for this.

See this is what years of enterprise computing in big teams did to me. I am out of touch with the big picture...
