### ISSUE TITLE
No Trade when short exchange price is greater than long exchange price

### ISSUE THREAD

**Issue by packetscaper** [butor/blackbird#182]
Why is there no trading opportunity when bitfinex price is less than bitstamp price ?
Isn't arbitrage opportunity still there as long as there is a spread either way ?

**Comment by greatwolf** [comment]
Short answer is because there's no way to take a short position on bitstamp on margin.

**Comment by packetscaper** [comment]
Ok I understood now. Shorting a stock which trades higher will not result in profit when spread decreases.

**Comment by butor** [comment]
@packetscaper You're correct, but it's more than that:

Let's say you have a spread between exchange _A_ and exchange _B_. _A_ is trading at a price higher than _B_:

- price on _A_: $1,200
- price on _B_: $1,000

As you can see, there is an arbitrage opportunity there. To simplify, let's say the whole bitcoin market doesn't move and let's see three basic scenarios where the spread might close:

- _A_ was off and is corrected:
price on _A_: $1,000
price on _B_: $1,000

- _B_ was off and is corrected:
price on _A_: $1,200
price on _B_: $1,200

- Both exchanges were off and both are corrected:
price on _A_: $1,100
price on _B_: $1,100

As you can see, during a correction the price on _A_ will always decrease relatively to _B_.
Conversely, _B_ will always increase relatively to _A_. Knowing that, you will always short sell the exchange with the higher price and buy the exchange with the lower price.

That example is an oversimplification, but since we are looking at the _difference_ between the prices, the behavior will remain the same even if the bitcoin market moves while doing arbitrage.

In the case of Blackbird, since Bitfinex is the only exchange where short selling is implemented, when its price is _below_ the others nothing will happen.
