### ISSUE TITLE
Blackbird for BTC - ETH, market neutral?

### ISSUE THREAD

**Issue by sulistyo** [butor/blackbird#193]
1. I see on the config that leg1 and leg2 can be modified. Is it possible if I want to trade arbitrage between BTC and altcoins such as ETH? 
2. Other than changing the config Leg1=ETH and Leg2 BTC, anything else I should do? 
3. Does this still considered market neutral since technically I would still have BTC, use it as my main trading currency, and the value of BTC could drop?
4. If it's not market neutral anyway can I still use blackbird and modified it to just long (buy) and sell directly?

**Comment by butor** [comment]
> I see on the config that leg1 and leg2 can be modified. Is it possible if I want to trade arbitrage between BTC and altcoins such as ETH?

Yes, we are indeed moving Blackbird to a more generic form, when you could trade any existing pairs instead of just BTC/USD. The implementation requires some changes in the codebase, and hasn't been completed yet.

> Other than changing the config Leg1=ETH and Leg2 BTC, anything else I should do?

When the change will have been implemented, you will need accounts in `Leg1` and `Leg2` currencies on the exchanges you want to trade.

> Does this still considered market neutral since technically I would still have BTC, use it as my main trading currency, and the value of BTC could drop?

That's an important point: yes you will be market neutral on `Leg1`, **but not** on `Leg2`. In a ETH/BTC arbitrage, it means that you will be hedged against market risk on ETH, but not on BTC. So the rationale in your question is correct.

> If it's not market neutral anyway can I still use blackbird and modified it to just long (buy) and sell directly?

No, Blackbird has been designed to do long/short arbitrage. You cannot go long only with it.

**Comment by sulistyo** [comment]
Awesome. Thank you for the explanation.

> That's an important point: yes you will be market neutral on Leg1, but not on Leg2. In a ETH/BTC arbitrage, it means that you will be hedged against market risk on ETH, but not on BTC. So the rationale in your question is correct.

That means we need to work with exchange that will support ETH marginal trading on both sides right?

**Comment by butor** [comment]
> That means we need to work with exchange that will support ETH marginal trading on both sides right?

Actually we need on _at least_ one side. If you look at the current BTC/USD implementation, we only have one side on margin, because for the moment we can only short sell on Bitfinex.

**Comment by Aviv972** [comment]
@butor Thank you very much for the great/professional answers!! can you please share with us the exchange that will allow you to short sell crypto pairs?

**Comment by greatwolf** [comment]
Just going off the time of my head, I believe the two obvious ones are Bitfinex and Polo. Kraken maybe another one but not too sure since I don't really use that exchange.

**Comment by Aviv972** [comment]
Hi Guys 

i'm trying to understand some of the blackbird parameters from the table above, can someone please explain them to me:

PriceDeltaLimit
TrailingSpreadLim
TrailingSpreadCount

Thank you.

**Comment by greatwolf** [comment]
Those have been asked before, see #66 and #72.

**Comment by eli124** [comment]
Is there a working implementation of BTC/ETH yet?  Or is that branch not available yet?
