### ISSUE TITLE
What's the point of this project?

### ISSUE THREAD

**Issue by tomekit** [butor/blackbird#208]
Hi,
This is not a technical question.
I've always tried to understand the open-source projects like this. What's the idea behind this project and your motivation behind as a project maintainer and lead dev.
This is free to use open-source project, meaning that everyone can use effectively competing with each other. 

Eventually (if project is popular enough), there won't be any meaningful opportunity for an individual investor / trader. It will become useless. Does it mean that project has succeeded or failed? :)

If your point was to make a profit, you probably would't keep the project available to anyone.

Is your point to improve market efficiency or perhaps this is something you enjoy working on in your free-time and something which might just improve your CV? :)

I would appreciate if you could tell me, what's the point. Much appreciated and good luck with Blackbird  <-- like that name.

**Comment by elsehow** [comment]
I am sure @butor could speak in more detail, but I will say briefly that arbitrage can add liquidity and efficiency to markets. Perhaps a greedy person would have the selfish motivation to do all this arbitrage themselves, but I think there is enough inefficiency for quite a few people :) And, by the time we have arbed "all" the inefficiencies away, we will have some better markets, which will allow for some more sophisticated (and reliable) market activity.

**Comment by jefferythewind** [comment]
This is a great question.  I can not speak for @butor either, but I do have some thoughts about it.  As an academic quant finance student, I could totally understand the argument to use this project to collect data, show what you can do, improve your CV.  And in this case it isn't just data, but real-world trading, which is often missing from academic research.

But otherwise, I would say your question comes from a traditional finance background, where you believe that what you know gives you some kind of edge, and if you tell other people what you know, you are giving away your edge, ie profits.  Well yes, I agree.

Although I would bring to your attention this new alt coin investment company i just heard a podcast about, which are trying to use the open source development paradigm as one of the research philosophies : https://ark-invest.com/open-research-ecosystem

> ARK’s Open Research Ecosystem is founded on the belief that transparent, collaborative, and interdisciplinary information flow will provide unique insights.

**Comment by Newar417** [comment]
How many Porsches do you need?
Would you be happier with 10 Porsches or would two suffice, knowing that you enabled eight other people to get a Porsche?

**Comment by butor** [comment]
It's indeed an interesting question that many people asked me. Here are a couple of reasons:

- _Intellectual curiosity_
This may seem straightforward, but thanks to Blackbird I had so many interesting discussions about trading, arbitrage, Bitcoin, C++, and so on. That reason is the number one about why I made Blackbird open source.

- _Building something cool, that trades on its on_
I've always been interested in automatic systems and all the challenges that come with it, specially when it involves trading. My C++ knowledge is limited (I'm not a developer), so I enjoy seeing the codebase being improved by more technical contributors.

- _Attempting to make good money with it still seems risky_
The profits made with arbitrage are usually a small percentage of the exposure. It means that to make good money, one needs to have a very high exposure in USD on the exchanges. Personally, I don't want to put too much money on Bitcoin exchanges. Everybody remembers Mt. Gox bankruptcy and Bitfinex hack...

Last but not least, I don't think having many people using Blackbird simultaneously is really a problem: due to many factors (strategy parameters, network latency, exposure, etc), people use Blackbird in different ways, and make profits from different opportunities.

**Comment by fredfortier** [comment]
Have you considered some kind of restricted license model? It's wonderful that small investors can chip away at exchange inefficiencies using this software. However, I can see others using it commercially in way which might not mesh with the benevolent spirit of this project.

**Comment by butor** [comment]
@fredfortier the license is the [MIT one](https://github.com/butor/blackbird/blob/master/LICENSE), which allows people to use it commercially. This is the most common license with this kind of open source projects, and I'm fine with that. Do you have another license in mind?

**Comment by fredfortier** [comment]
@butor to be honest, I'd personally rather see this project closed source. 

I totally respect your intellectual curiosity. This project is an amazing proof of concept. However, in maintenance mode (adding exchanges and currency pairs), it stops solving interesting problems. 

Some of the recent questions (e.g. #223) suggest that new entrants might see this project simply as a push-button solution to make a buck. Others might use it to create the next get-rich-quick cloud offering. I might be old school, but I like to see people working a bit harder for their alpha.

To answer your question more directly, a GPL license would at least force others to keep their software open-source, but it probably won't make much of a difference in practice.
