### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by vanikalapciev** [butor/blackbird#268]
I have some questions about the arbitrage script.

1. Are the arbitrages continous?

2. What combinations does it run? Lets say looking to my log here it sems it ony makes them towards XYZ/bitfinex:
```
OKCoin/Bitfinex:     -5.47% [target  0.80%, min -5.47%, max -5.47%]
Bitstamp/Bitfinex:    1.33% [target  0.80%, min  1.33%, max  1.33%]
Gemini/Bitfinex:      0.22% [target  0.80%, min  0.22%, max  0.22%]
Kraken/Bitfinex:     -0.00% [target  0.80%, min -0.00%, max -0.00%]
ItBit/Bitfinex:       0.14% [target  0.80%, min  0.14%, max  0.14%]

Does is also make other permutations like:

OKCoin/Bitstamp
Gemini/Kraken
ItBit/Bitsamp
...
All of permutations?

**Comment by bertrandfalguiere** [comment]
1.What do you mean?

2.What I understood from Blackbird is that it is market-neutral (making money out of the spread, independently the rise of fall of BTC over USD). To do this, it need a short position and a long one. Bitfinex is the only implemented exchange with short selling enabled over an API for Bitcoin. 
So the only opportunities Blackbird can catch is when the Bitfinex price is above another exchange price, and that's why you only see XYZ/Bitfinex. Blackbird will never make a trade Gemini/Kraken because Kraken does not enable short selling. 
To better understand why Blackbird needs shortselling to be market neutral, see issue #100.

**Comment by vanikalapciev** [comment]
thank oyu!
