### ISSUE TITLE
Why are you using "limit" orders? an not "market"?

### ISSUE THREAD

**Issue by gilamran** [butor/blackbird#363]
I saw that you are using "limit" order, why not market?
limit orders are not guaranteed to get fulfilled...

**Comment by alfonsoperez** [comment]
but market orders don't guarantee the price, so that you don't really have fine grained control, that's why blackbird uses the configurable setting 'OrderBookFactor', that basically makes it so it enforces by default 3 times the required volume. I guess improvements could be made around this and if orders don't get fulfilled at the same time and thus there is slippage see how blackbird could recover from this

**Comment by gilamran** [comment]
@alfonsoperez why do you say that "market" orders don't guarantee price? isn't that's the only reason for market orders? "limit" orders are not guaranteed, as they mark a limit to the order... in "market" orders, you buy at any price.

**Comment by gilamran** [comment]
Well, as you said, the 'OrderBookFactor' covers this situation. because it's set to x3 by default...
It's not optimal, but it's some protection

**Comment by alfonsoperez** [comment]
Yes, depending upon the volatility I guess you could tweak it. As a naive protection I think suits a big part of this.
