### ISSUE TITLE
Question: How blackbird manage balances?

### ISSUE THREAD

**Issue by hugofreire** [butor/blackbird#374]
In the long term its possible to have less and less money in the one account right?
How blackbird balance the two accounts or we have to manage our selves. 

Sry for my bad english.
Thanks in advance :)

**Comment by itskeKs** [comment]
it does not move your money from one to another. it just uses the balance you have. i guess as long as your max used exposure ist not higher then your balance it will work. lesser balance than maxexposure might result in errors since the bot will try to buy or bet with more money then available (just a guess).

**Comment by hugofreire** [comment]
I know but its possible to make "plays" that even the two accounts?
If i star with 1000€ each and set a max exposure of 100€ it can run for ever?

**Comment by itskeKs** [comment]
yes it will only bid for shorting for max 100 (the amount which will be used might be less since you have some leverage added by the exchange) and buy long for max 100 (this one will always be max exposure since it actually buys BTC for long run).

currency should be $ and not €

**Comment by hugofreire** [comment]
Thanks itskeks, one more question
## log
OKCoin/Bitfinex:     -6.28% [**target  0.80%**, min -7.00%, max -5.22%]

The target its configurable and is the profit we aim to reach/search?

**Comment by hugofreire** [comment]
Ok i already read in the docs, target 0.80% is the spread entry  :) 
Thanks itskeks
