### ISSUE TITLE
All opportunities are in minus

### ISSUE THREAD

**Issue by rubiwane** [butor/blackbird#377]
Does someone can explain this?
Since 3 days all opportunities are in minus
[ 01/10/2018 09:25:06 ]
   Bitfinex: 	13,587.00 / 13,588.00
   Kraken: 	13,764.50 / 13,770.00
   ItBit: 	13,681.43 / 13,685.10
   QuadrigaCX: 	13,569.08 / 13,999.26
   ----------------------------
   Kraken/Bitfinex:	**-1.33%** [target  0.80%, min -3.25%, max  1.15%]
   ItBit/Bitfinex:	**-0.72%** [target  0.80%, min -2.27%, max  0.24%]   info only
   QuadrigaCX/Bitfinex:	**-2.94%** [target  0.80%, min -10.88%, max -0.29%]

**Comment by asloveus** [comment]
It's because the current spread between Kraken and Bitfinex (-1.33%) is below the target (0.80%),  current spread between ItBit and Bitfinex (-.72%) is below the target (0.80%)
and so on....

**Comment by skopanev** [comment]
Why not to use Bitfinex/Kraken then?

**Comment by asloveus** [comment]
Kraken only short with 5:1.

Is it 5:1 spread? No. Therefore no Bitfinex/Kraken.

**Comment by HashDeCoder** [comment]
5:1 Has to do with leverage, diffrent leverage is not a problem as long as the bot picks the same lotsize.

**Comment by LasseMoench** [comment]
Since Kraken short selling is supported now, it should be possible to trade in both directions between kraken and bitfinex, so as long as there is a spread, there will be an arbitrage opportunity. Maybe you can test this with the current version, I can't open a bitfinex account since I don't have 10,000USD lying around :)
