### ISSUE TITLE
Nonce is too small

### ISSUE THREAD

**Issue by kokomoji** [butor/blackbird#38]
Hello,
@butor 

After i change Demo to "false" and add api in blackbird.conf , it shows:

Blackbird Bitcoin Arbitrage Log File
Blackbird started on 01/16/2016 12:12:10

[ Targets ]
Spread Entry: 0.80%
Spread Target: 0.20%

[ Current balances ]
Error with JSON: {"message": "Nonce is too small."}. Retrying...
Error with JSON: {"message": "Nonce is too small."}. Retrying...

**Comment by butor** [comment]
Hi @kokomoji,

I already had this issue in the past: usually it's because one day you used a larger nonce with these credentials. The nonce has to be always increasing.

To fix this problem, create a new API key on Bitstamp, then update `BitstampApiKey` and `BitstampSecretKey` in the config file with the new key. This should fix the problem.

**Comment by butor** [comment]
Hi @kokomoji,

I already had this issue in the past: usually it's because one day you used a larger nonce with these credentials. The nonce has to be always increasing.

To fix the problem recreate the API keys on the exchange where you have the issue, then update _blackbird.conf_ with the new credentials and restart Blackbird. It should fix the problem.

To know what exchange is concerned check the beginning of the error message in the log file, e.g.:

```
<EXCHANGE_NAME> Error with JSON: {"message": "Nonce is too small."}. Retrying...
<EXCHANGE_NAME> Error with JSON: {"message": "Nonce is too small."}. Retrying...
```

**Comment by kokomoji** [comment]
Hi ,
@butor  
It's working! Thanks for your help! ~

**Comment by butor** [comment]
My pleasure!
