### ISSUE TITLE
Warning: WARNING: 2 second(s) too late at...

### ISSUE THREAD

**Issue by pepijnolivier** [butor/blackbird#39]
I'm about to try out blackbird, but I'm hesitant as in the logs I keep seeing messages like:

> WARNING: 2 second(s) too late at 01/18/2016 01:16:33

On **every** iteration I get a warning message like this.Sometimes it's 1 second, sometimes it's 18. What exactly does this mean and how can I make sure the process moves faster?

- I'm not on a slow internet connection
- I'm not on a slow computer
- I'm located in Belgium
- (I'm currently still in demo mode)

Thanks for any input!

**Comment by butor** [comment]
Hi @pepijnolivier,

Blackbird downloads and analyzes the data in loop, every `GapSec` seconds. By default that loop parameter is set to 3 seconds (`GapSec=3.0`). You can increase this loop, e.g. `GapSec=10.0`, and most of your warnings should disappear. Increasing the loop shouldn't impact the market neutrality but you might miss short arbitrage opportunities.

A warning tells you that the download + analysis weren't able to be completed within `GapSec` seconds. The analysis phase is always very fast, so having many warnings is usually due to a latency in the price downloads. Do you face any other network latency with your machine?

As reference, I run Blackbird 24/7 on a Google Cloud machine, with `GapSec=3.0`, and I get a warning (usually 1 second) every 5 to 10 minutes. Note that these warnings shouldn't impact the system to much.

**Comment by pepijnolivier** [comment]
@butor Thanks, setting `GapSec=10.0` gets rid of all these warnings. :) I shouldn't have any network latency, but I'm going to test this out on a different connection just to make sure.

As a sidenote, what would be a good minimum dollar value required on each exchange to make a steady amount of trades? I can imagine having only 50$ on each exchange might not result in many (if any) trades.

**Comment by butor** [comment]
@pepijnolivier The minimum amount I recommend is $10 per exchange (parameter `CashForTesting`).

Actually, the USD exposure won't impact the _number_ of trades generated. However, since the returns are low (close to the parameter `SpreadTarget`), a small USD exposure will generate very tiny returns.

**Comment by 360disrupt** [comment]
@butor: 
If the warning is `Xs`, this means in the worst case, that between the first query response and the last query response are `Xs`? So this could theoretically impact market neutrality if the course change is big in that time?

**Comment by butor** [comment]
Hi @360disrupt,

The `GapSec` value only represents the size of the _analysis loop_. That loop contains the following steps:

1. Download the bid/ask prices for every exchange
2. Compute the spreads for every combination and check whether the spreads are above `SpreadEntry`.

If `GapSec` is 5 seconds, it means that the two steps above are executed every 5 seconds.

That being said, once an arbitrage opportunity is detected then the two orders are sent _simultaneously_. The only market risk occurs when an order is completely filled while the other is still open. But since we are using aggressive limit prices (_crossing the spread_), the executions of the two orders should be almost immediate, so that the market risk is very short.
