### ISSUE TITLE
Kraken Error with JSON: {"error": [], "result": {}}.

### ISSUE THREAD

**Issue by Insaned79** [butor/blackbird#47]
Getting this error while trying to add Kraken API  #key:
<Kraken> Error with JSON: {"error": [], "result": {}}

**Comment by butor** [comment]
HI @Insaned79,

Could you please show us the full log file? Just remove any information you think is sensitive (e.g. the balances on your accounts).

Thanks

**Comment by Insaned79** [comment]
```
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 02/08/2016 17:13:29

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.30%

[ Current balances ]
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...
<Kraken> Error with JSON: {"error": [], "result": {}}. Retrying...

```

**Comment by butor** [comment]
Thank you @Insaned79. It looks like the Kraken implementation doesn't work correctly. I'll take a look to the code soon.

**Comment by Insaned79** [comment]
if it helps - I can give you (via email) my key to test (account is empty now)

**Comment by butor** [comment]
@Insaned79 that would be helpful thanks (julien.hamilton@gmail.com). I'll tell you when I'm done so you'll be able to delete it and recreate a new one.

**Comment by butor** [comment]
Issue fixed. Cause: Kraken returns an empty JSON object whenever all the accounts are empty (i.e. BTC=0.00, USD=0.00, EUR=0.00). I've contacted Kraken as I think they should return this:

```
{"error":[],"result":{"ZUSD":"00.0000","ZEUR":"0.0000","XXBT":"0.0000000000"}}
```

instead of this:

```
{"error": [], "result": {}}
```

This is how the other Bitcoin exchanges deal with empty accounts. Kraken shouldn't return an empty JSON object.

Anyway, Blackbird will now return 0.00 if the JSON object is empty when checking the balances on Kraken. Thanks @Insaned79 for the assistance.
