### ISSUE TITLE
Question about log output.

### ISSUE THREAD

**Issue by GuySawyer** [butor/blackbird#64]
Running Blackbird in demo mode, I have this log output:

>[ 06/01/2016 08:44:24 ]
   Bitfinex: 	531.04 / 531.10
   OKCoin: 	534.82 / 535.45
   Bitstamp: 	530.94 / 531.26
   Gemini: 	531.12 / 532.02
   Kraken: 	529.43 / 530.00
   ItBit: 	532.27 / 532.31
   BTC-e: 	519.07 / 517.32
   796.com: 	546.17 / 550.60
   Poloniex: 	524.00 / 527.39
   ----------------------------
   Bitfinex/Poloniex:	-1.34% [target  0.10%, min -1.46%, max  0.45%]
   OKCoin/Bitfinex:	-0.82% [target  0.10%, min -0.85%, max  0.75%]
   OKCoin/Poloniex:	-2.14% [target  0.10%, min -2.16%, max  0.88%]
   Bitstamp/Bitfinex:	-0.04% [target  0.10%, min -0.68%, max  0.76%]
   Bitstamp/Poloniex:	-1.37% [target  0.10%, min -1.50%, max  0.29%]
   Gemini/Bitfinex:	-0.18% [target  0.10%, min -0.71%, max  0.55%]
   Gemini/Poloniex:	-1.51% [target  0.10%, min -1.58%, max  0.42%]
   Kraken/Bitfinex:	 0.20% [target  0.10%, min -0.86%, max  1.20%]   trailing  0.10%  0/2
   Kraken/Poloniex:	-1.13% [target  0.10%, min -1.58%, max  0.87%]
   ItBit/Bitfinex:	-0.24% [target  0.10%, min -0.82%, max  0.74%]
   ItBit/Poloniex:	-1.56% [target  0.10%, min -1.79%, max  0.45%]
   BTC-e/Bitfinex:	 2.65% [target  0.10%, min  0.00%, max  3.82%]
   BTC-e/Poloniex:	 1.29% [target  0.10%, min  0.00%, max  2.51%]
   796.com/Bitfinex:	-3.55% [target  0.10%, min -4.73%, max -2.84%]
   796.com/Poloniex:	-4.83% [target  0.10%, min -5.49%, max -2.93%]
   Poloniex/Bitfinex:	 0.69% [target  0.10%, min -0.86%, max  1.02%]
   -
   WARNING: 8 second(s) too late at 06/01/2016 08:44:27`

How would I know if there was a possible successful trade?
Would the csv output file actually be written to with demo data of trades that could have occurred?
What does the warning mean??

Bonus question: Which section of the code do I need to edit in order to only use certain exchanges?
I can't find anything to configure in the .conf?

**Comment by butor** [comment]
> How would I know if there was a possible successful trade?

If a potential trade opportunity comes up, you will see the following line in the log file:

```
INFO: Opportunity found but no trade will be generated (Demo mode)
```

> Would the csv output file actually be written to with demo data of trades that could have occurred?

No, in Demo mode nothing is written in the csv file.

> What does the warning mean ("WARNING: 8 second(s) too late at 06/01/2016 08:44:27")?

It means that your system took too long to complete the iteration (the analysis loop) in the time lapse defined by the parameter GapSec. You can increase that parameters (e.g. GapSec=15.0) to make the warnings disappear. The only drawback is that you might miss arbitrage opportunities because the analysis will occur every 15 seconds instead of every 3 seconds.

> Which section of the code do I need to edit in order to only use certain exchanges?

In Demo mode, all the exchanges for which we have the bid/ask information are displayed. In real trading, only the exchanges for which you put credentials in the config file will be automatically used.

**Comment by GuySawyer** [comment]
Thank you for your response.

With regards to the GapSec, why might my system be taking so long, how can I improve the analysis loop speed?

**Comment by butor** [comment]
Usually it's due to the network latency when the quotes are downloaded
