### ISSUE TITLE
Questions: Settings

### ISSUE THREAD

**Issue by 360disrupt** [butor/blackbird#72]
# Settings
- `MaxLength`: So this is how often the 3s cycle is run until the app quits. What is the maximum number, can it be set to infinite (e.g. -1). Whats the purpose?
- `DebugMaxIteration`: Whats the difference to `MaxLength`?
- `SpreadEntry` & `SpreadTarget ` So the smaller `SpreadEntry` is the bigger `SpreadExit` gets. That means if `SpreadEntry` is higher more opportunities occur?  Or asked the other way around the holding time increases when `SpreadEntry` is lower? So a good value is probably that `SpreadEntry` & `SpreadExit` are close to each other => most trades
- `PriceDeltaLimit ` ?
- `TrailingSpreadLim ` => [This](https://github.com/butor/blackbird/issues/12) could be helpful in the Readme
- `TrailingSpreadCount` in iterations, so `1` with a `GapSec ` of `3` would be `3s`?

# Rising/Falling Charts
What would happen if both markets rise after the entry.

e.g. 
target 1.5%
entry 1%

T1:
Market A Short: 100$ 
Market B Long: 99$
(+1%) > market is entered

T2: 
Market A Short: 110$
Market B Long: 111$
(-0.9%) > market would be exited but not all trades are possible?

If the bot uses full cash, it won't be able to rebuy the coins on market A even if there is an exit option.

Sorry for asking so many questions but some of the config params are not 100% clear to me, I'm more a programmer (unfortunately not C) than finance guy ;-) .

**Comment by butor** [comment]
@360disrupt:
- What you are describing is actually `DebugMaxIteration` with a default limit of 3.2 millions iterations. This is simply used for troubleshooting Blackbird with return=0. `MaxLength` is the maximum length of a _trade_, which is 60 days per default. This is used if you want to exit a trade regardless of the profit (or loss), so no trade might stay open forever. This is a way to cancel an open arbitrage trade. Please use a large value.

- It's actually the opposite: the higher `SpreadEntry` is, the fewer opportunities come up. A higher `SpreadEntry` means that the discrepancies between the prices must be higher which is less common that small discrepancies. If you want more trades but with lower profit each, you need to have a small `SpreadEntry` _and_ a small `SpreadTarget`.

- `PriceDeltaLimit`: The maximum difference between the target limit price and the computed limit price of an order. That is the price generated by looking at the current liquidity in the order books. If the difference is greater than PriceDeltaLimit then no trades will be generated because there is not enough liquidity (risk of slippage).

- `TrailingSpreadCount` is a real counter and not a value in seconds. It is not related to `GapSec`.

- Bitfinex manages the losses on short selling automatically: you don't actually need to "rebuy" the bitcoins. Bitfinex will handle all that part for you. So if you have $100 on your account, open a short sell position at $100 then you close the position at $110, you will simply have $90 left on your account (loss of $10).

**Comment by Jay54520** [comment]
> Blackbird will set the exit threshold at -0.70%

What is "threshold", how does the program use it?

**Comment by Jay54520** [comment]
> The maximum difference between the target limit price and the computed limit price of an order.

What are "target limit price" and "computed limit price". I think they can be the market price if the market price meet `SpreadEntry` and `OrderBookFactor `.

**Comment by Jay54520** [comment]
Why need "TrailingSpreadCount"? To reduce slippage?
